/* TENN Bukit Baru — seed data.
   SEED_BQ: line items from the tender BQ (unpriced).
   SEED_AREAS: work areas + procurement buy-list from the Procurement List
   (read against ID drawings 260710-Amended and Tender Clarifications 04 Mar 2025).
   Key clarifications baked into specs: gold strips = SS gold finish (#10);
   counter tops = colour glass (#6); toilet basin tops = granite (#9);
   utility door = hidden type (#5); TV walls get extra backing (#4). */
'use strict';

const SEED_BQ = [
  { code: "P", title: "PRELIMINARIES", items: [
    { code: "1", desc: "Insurance (Car, WC)", unit: "L/sum", qty: 1, rate: 0 },
    { code: "2", desc: "All cost for preliminaries for overall works (Main Lobby, Show Unit Type A & Type B)", unit: "L/sum", qty: 1, rate: 0 },
  ] },
  { code: "L", title: "MAIN LOBBY", items: [
    { code: "1", desc: "[A. Reception Counter Table] Reception Table Counter comes with drawer and lock key set, complete with Top colour tempered glass , Marble finishes with code (TP7-53011G VOLAKAS), white glossy laminate (counter centre part), black glossy laminate for bottom part of counter, light trough/cove, opening for switches, top desk, table desk, keylock, etc all to refer 3D and ID's Details Drawing.", unit: "Lot", qty: 1, rate: 0 },
    { code: "2", desc: "[A. Reception Counter Table] To include supply & install LED light strip, driver, casing and light cover (flosted)", unit: "Lot", qty: 1, rate: 0 },
    { code: "3", desc: "[B. Front Backdrop behind Reception] Wall panel with TP6-3361-M Midnight Marble Finishes (Topmix) c/w 20mm gold strip and 20mm Black Fluted Panel, Wall panel with TP7-53011G VOLAKAS-Marble Finishes c/w 20mm gold strip for centre part, backdrop LED light and including both sides panels with bronze mirror with LED lighting etc all as per 3D & ID's Details Drawings.", unit: "Lot", qty: 1, rate: 0 },
    { code: "4", desc: "[B. Front Backdrop behind Reception] -supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 1, rate: 0 },
    { code: "5", desc: "[C. Left Side Wall (Company Milestones' Wall)] Wall panel with TP7-53011G Volakas- Marble Finishes c/w 20mm gold strip, 20mm Black Fluted Panel, all with 20mm gold strip, LED light with casing etc all as per 3D & ID's Details Drawings.", unit: "Lot", qty: 1, rate: 0 },
    { code: "6a", desc: "[D. ID Wall Finishes @ Front Show Unit Area] a) for front area at Show Unit Type A", unit: "Lot", qty: 1, rate: 0 },
    { code: "6b", desc: "[D. ID Wall Finishes @ Front Show Unit Area] b) for Front area at Show Unit Type B", unit: "Lot", qty: 1, rate: 0 },
    { code: "7", desc: "[E. Sitting & Discussion Area, Pantry & Utility] Wall panel with TP7-53011G Volkas- Marble Finishes c/w 20mm Gold strip,Bronze Mirror Wall Panel with LED Backlight etc. all as per ID Drawings. *Note: Required add additional backing support for Advertising panel area & TV Area; Advertising Panel area is recess back; supply & install advertising panel by other.", unit: "Lot", qty: 1, rate: 0 },
    { code: "8", desc: "[F. Counter Table 02] Counter Table complete with Top colour tempered glass , Marble finishes with code (TP7-53011G VOLAKAS), 20mm Black Fluted Panel, TP6-3361-M Midnight Marble Finishes for above & bottom part of counter, light trough/cove, opening for switches, top desk, table desk, keylock, etc all to refer 3D and ID's Details Drawing.", unit: "Lot", qty: 1, rate: 0 },
    { code: "9", desc: "[F. Counter Table 02] To include supply & install LED light strip, driver, casing and light cover (flosted)", unit: "Lot", qty: 1, rate: 0 },
    { code: "10", desc: "[G. Advertising Wall near Show Unit] Bronze Mirror Wall Panel with LED Backlight etc. all as per ID Drawings.", unit: "Lot", qty: 1, rate: 0 },
    { code: "11", desc: "[H. Pantry Cabinet] Pantry Cabinet in Black galaxy stone counter top (to client selection) and side c/w gray colour glass on doors, drawer & shelves etc all as per ID Drawings **To add aluminium shelves on top of Pantry Cabinet (refer 3D Drawings) (Single Bowl Sink & Water Tap by other)", unit: "Lot", qty: 1, rate: 0 },
    { code: "12a", desc: "[Public Toilet Mirror] a) Male Toilet: Size ± 1950mm x 900mm height", unit: "Lot", qty: 1, rate: 0 },
    { code: "12b", desc: "[Public Toilet Mirror] -supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 1, rate: 0 },
    { code: "12c", desc: "[Public Toilet Mirror] b) Female Toilet: Size ± 2750mm x 900mm height", unit: "Lot", qty: 1, rate: 0 },
    { code: "12d", desc: "[Public Toilet Mirror] -supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 1, rate: 0 },
  ] },
  { code: "M", title: "LOBBY — MODEL HOUSE BASE", items: [
    { code: "1", desc: "[A. Model House Bench] To construct a model house base structure to carpenter details, c/w 20mm(H) RIM Boarder with laminate finish (Code: TP7 53011G VOLAKAS -MARBLE FINISHES) with black paint on top of base, black glossy laminate. LED light all details to follow ID's drawing.", unit: "Lot", qty: 1, rate: 0 },
  ] },
  { code: "G", title: "LOBBY — GARDEN SEATING AREA", items: [
    { code: "1", desc: "[A. Sitting Area 01] To construct a seating bench with timber finish details all to follow details drawing", unit: "Lot", qty: 1, rate: 0 },
    { code: "2", desc: "[A. Sitting Area 01] To construct planter box with textured finish details all to follow details drawing", unit: "Lot", qty: 1, rate: 0 },
    { code: "3", desc: "[B. Sitting Area 02] To construct a seating bench with timber finish details all to follow details drawing.", unit: "Lot", qty: 1, rate: 0 },
    { code: "4", desc: "[B. Sitting Area 02] To construct planter box with textured finish details all to follow details drawing.", unit: "Lot", qty: 1, rate: 0 },
  ] },
  { code: "A", title: "SHOW UNIT TYPE A (2 BEDROOMS)", items: [
    { code: "1", desc: "[A. Living Hall TV Area — Back Panel] Marble effects laminate (Code: TP6-3321-G (Topmix) c/w Gold laminate with LED Light c/w Built- In TV cabinet with glossy beige laminate (Code: TS7-6026-G-Creamy) all design as per client's selection, light cove, etc all as per ID's Drawings. (To add additional structure support for TV installation)", unit: "Lot", qty: 1, rate: 0 },
    { code: "2", desc: "[A. Living Hall TV Area — Back Panel] Supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 1, rate: 0 },
    { code: "3", desc: "[B. Dining Area — Marble Effect & Wainscoting Wall] 25mm wainscotting wall panel (pattern to client's selection), 20mm wall fluted panel c/w 10mm gold strip and tea mirror, all design as per client's selection, light cove, etc all as per ID's Drawings.", unit: "Lot", qty: 1, rate: 0 },
    { code: "4", desc: "[B. Dining Area] Supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 1, rate: 0 },
    { code: "5", desc: "[C. Living Hall — Behind Sofa Area] 20mm Wood Grain Beige Fluted Wall panels c/w Glossy beige laminate with 10cm glod strip (Code: TS7-6026-G-CREAMY) (all profile and pattern to client selection), painting, etc. all as per ID drawings.", unit: "Lot", qty: 1, rate: 0 },
    { code: "6", desc: "[D. Dining Hall & Kitchen/Yard] 20mm beige fluted wall panel c/w marble effect laminate (pattern to client's selection), tea mirror, Glossy beige laminate with 10mm gold strip (Code: TS7-6026-G-CREAMY) with LED backlight, light cove, painting, etc all as per ID's Drawings", unit: "Lot", qty: 1, rate: 0 },
    { code: "7", desc: "[D. Dining Hall & Kitchen/Yard] -supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 1, rate: 0 },
    { code: "8", desc: "[E. Master Bedroom] Bedhead with fabric finish, Fabric wall panel c/w 75mm gold laminate, Marble effect laminate with LED strip (Code: TP7-53018M-VOLAKAS) etc. all as per ID drawings", unit: "Lot", qty: 1, rate: 0 },
    { code: "9", desc: "[E. Master Bedroom] -supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 1, rate: 0 },
    { code: "10", desc: "[E. Master Bedroom] Bedside table", unit: "no", qty: 1, rate: 0 },
    { code: "11", desc: "[F. Master Bedroom (Built-in Cabinet)] Built in cabinet c/w Glossy Beige laminate (Code: TS7-6026-G-CREAMY), Wood grain laminate (Code: TW10-53706 IM BOLZANO WALNUT), 5mm Groove Line etc. all as per ID drawings.", unit: "Lot", qty: 1, rate: 0 },
    { code: "12", desc: "[F. Master Bedroom (Built-in Cabinet)] -supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 1, rate: 0 },
    { code: "13", desc: "[G. Bedroom 01] Glossy beige laminate bedhead with 5mm groove line (Code: TS7-6026-G-CREAMY), Glossy Beige Laminate wall panel with LED strip (Code:TS7-6026-G-CREAMY), Fabric wall panel, Tea mirror with 5mm groove line etc. all as per ID drawings", unit: "Lot", qty: 1, rate: 0 },
    { code: "14", desc: "[G. Bedroom 01] Supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 1, rate: 0 },
    { code: "15", desc: "[G. Bedroom 01] Bedside table c/w wood grain laminate (Code: Top Mix TW10-53006 VM ASAPH ASH), Glossy Beige Laminate (Code; TS7-6026 G CREAMY) all as per ID's Drawings.", unit: "no", qty: 1, rate: 0 },
    { code: "16", desc: "[H. Bedroom 01 (Built-in Cabinet)] Built in cabinet c/w wood grain laminate shelves with LED Strip (Code: TW10-53006 VM ASAPH ASH), Wood grain laminate (Code: Top Mix TW10-53006 VM ASAPH ASH), Glossy Beige laminate (Code: TS7-6026 G CREAMY) etc. all as per ID drawings.", unit: "Lot", qty: 1, rate: 0 },
    { code: "17", desc: "[H. Bedroom 01 (Built-in Cabinet)] -supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 1, rate: 0 },
    { code: "18", desc: "[I. Bathroom 1 & 2] Supply & install toilet vanity cabinet in Gray laminate (Code: TS4-1227 Dim Grey (Top Mix) finish c/w 100mm thick Quartz Stone counter top (including opening for Table Top basin) to details ID's drawings. (Material type, colour & finishes to the Client selection) overall size : ± 500mm (L) x 450mm (W) x 400mm (H) *Quartz stone 100mm height", unit: "Lot", qty: 2, rate: 0 },
    { code: "19", desc: "[I. Bathroom 1 & 2] Supply & install toilet Full height Glass Mirror (in bronze colour or subject to Client final decision). Complete with LED light cove. Size ± 900mm Height x 1520mm (Length)", unit: "Lot", qty: 2, rate: 0 },
    { code: "20", desc: "[I. Bathroom 1 & 2] -supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 2, rate: 0 },
    { code: "21", desc: "[J. Door Frame] 70mm Wood Grain Laminate Door Frame (Code: TW8-3786VF ERFURT ACACIA) all as client selection etc. (for Main foyer, Master bed, bedroom 2, bath 1 & 2, kitchen/yard door)", unit: "no", qty: 6, rate: 0 },
  ] },
  { code: "B", title: "SHOW UNIT TYPE B (3 BEDROOMS)", items: [
    { code: "1", desc: "[A. Living Hall — Sofa Area] 20mm Wood Grain Fluted panel c/w Matte light grey laminate with 5mm groove line (Code: TS4-1223 GAINSBORO GREY) ) all design as per client's selection, light cove, etc all as per ID's Drawings. (To add additional structure support for TV installation)", unit: "Lot", qty: 1, rate: 0 },
    { code: "2", desc: "[A. Living Hall — Sofa Area] Supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 1, rate: 0 },
    { code: "3", desc: "[B. Living Hall TV Area — Back Panel] Marble effects laminate (Code: TP6-3331-G Levanto Marble) c/w 5mm groove line, Wood effect laminate with 5mm groove line (Code: TW8-3758 SE SOKOTO CHESTNUT), 10mm Gold Strip c/w Built- In TV cabinet with glossy black laminate (Code: TS6-5018 G BLACK), marble effect laminate (Code: TP6-3331 G LEVANTO MARBLE), Tea mirror, all design as per client's selection, light cove, etc all as per ID's Drawings. (To add additional structure support for TV installation)", unit: "Lot", qty: 1, rate: 0 },
    { code: "4", desc: "[B. Living Hall TV Area — Back Panel] Supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 1, rate: 0 },
    { code: "5", desc: "[C. Dining Area] Matte light grey laminate with 5mm groove line (Code: TS4-1223 GAINSBORO GREY), 5mm groove line at 750mm height, Marble Effect laminate (Code: TP6-3331 G LEVANTO MARBLE) , Wood effect laminate with 5mm groove line (Code: TW8-3758 SE SOKOTO CHESTNUT), Tea Mirror with LED light , all design as per client's selection, light cove, etc all as per ID's Drawings.", unit: "Lot", qty: 1, rate: 0 },
    { code: "6", desc: "[C. Dining Area] Supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 1, rate: 0 },
    { code: "7", desc: "[D. Master Bedroom] 1000mm Fabric Bedhead with LED Backlight c/w 25mm wood fluted panel on top of bed head. Marble effect laminate with 5mm Groove line (Code:TP7-53015 G IMOLA MARBLE) c/w 10mm Gold strip for Back Panel, Wall Panel with 20mm wainscottting to client selection etc. all as per ID drawings.", unit: "Lot", qty: 1, rate: 0 },
    { code: "8", desc: "[D. Master Bedroom] -supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 1, rate: 0 },
    { code: "9", desc: "[D. Master Bedroom] Bedside table c/w Wood grain effect laminate (Code: TW8-3758 SE SOKOTO CHESTNUT), Glossy Gray Laminate (Code: TS6-5223 G GAINSBORO GREY) etc all as per ID's Drawing.", unit: "no", qty: 2, rate: 0 },
    { code: "10", desc: "[E. Master Bedroom (Built-in Cabinet)] Built in cabinet c/w Wood grain effect laminate with 5mm groove line (Code: TW8-3758 SE SOKOTO CHESTNUT), Gray laminate with 5mm groove line (Code: TS6-5223 G GAINSBORO GREY), 5mm Groove Line etc. all as per ID drawings.", unit: "Lot", qty: 1, rate: 0 },
    { code: "11", desc: "[E. Master Bedroom (Built-in Cabinet)] Dressing table with Wood grain effect laminate backing (Code: TW8-3758 SE SOKOTO CHESTNUT) c/w mirror with LED Backlight, Wood grain effect laminate for top (Code: TW8-3758 SE SOKOTO CHESTNUT) c/w laminated drawer with (Code: TS6-5223 G GAINSBORO GREY) etc all as per ID's Drawings.", unit: "Lot", qty: 1, rate: 0 },
    { code: "12", desc: "[E. Master Bedroom (Built-in Cabinet)] -supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 1, rate: 0 },
    { code: "13", desc: "[F. Bedroom 01] Wood grain laminated bedhead (Code: M30207 Messiera Cherry (Maica) )with 25mm wood fluted panel, (Bed base by carpenter's details) with LED strip all as per ID drawings.", unit: "Lot", qty: 1, rate: 0 },
    { code: "14", desc: "[F. Bedroom 01] Supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 1, rate: 0 },
    { code: "15", desc: "[G. Bedroom 01 (Built-in Cabinet)] Built in cabinet c/w Glossy Grey laminate (Code: TS6-5223 G GAINSBORO GREY) c/w wood grain laminate (Code: M30207 Messiera Cherrry (Maica) )wood grain laminate backing, handle & desk top (Code: M30207 Messiera Cherry (Maica) ) with LED Strip etc. all as per ID drawings.", unit: "Lot", qty: 1, rate: 0 },
    { code: "16", desc: "[G. Bedroom 01 (Built-in Cabinet)] -supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 1, rate: 0 },
    { code: "17", desc: "[H. Bedroom 02] Fabric wall panel c/w marble effect laminate with LED light (Code: TP7-53011 G VOLAKAS MARBLE) etc. all as per ID drawings", unit: "Lot", qty: 1, rate: 0 },
    { code: "18", desc: "[H. Bedroom 02] Supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 1, rate: 0 },
    { code: "19", desc: "[I. Bedroom 02 (Built-in Cabinet)] Built in cabinet c/w Glossy Beige laminate (Code: TS7-6026 G CREAMY) and Tea Mirror, Wood grain laminate (Code: M3042 English Oak (Maica) ) for shelves with LED Strip etc. all as per ID drawings.", unit: "Lot", qty: 1, rate: 0 },
    { code: "20", desc: "[I. Bedroom 02 (Built-in Cabinet)] -supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 1, rate: 0 },
    { code: "21", desc: "[J. Bathroom 1 & 2] Supply & install toilet vanity cabinet in Gray laminate (Code: TS4-1227 Dim Grey (Top Mix) finish c/w 100mm thick Quartz Stone counter top (including opening for Table Top basin) to details ID's drawings. (Material type, colour & finishes to the Client selection) overall size : ± 500mm (L) x 450mm (W) x 400mm (H) *Quartz stone 100mm height", unit: "Lot", qty: 2, rate: 0 },
    { code: "22", desc: "[J. Bathroom 1 & 2] Supply & install toilet Full height Glass Mirror (in bronze colour or subject to Client final decision). Complete with LED light cove. Size ± 900mm Height x 1140mm (Length)", unit: "Lot", qty: 2, rate: 0 },
    { code: "23", desc: "[J. Bathroom 1 & 2] -supply and install LED light strip c/w driver and accessories", unit: "Lot", qty: 2, rate: 0 },
    { code: "24", desc: "[K. Door Frame] 70mm Wood Grain Laminate Door Frame (Code: TW8-3786VF ERFURT ACACIA) all as client selection etc. (for Main foyer, Master bed, bedroom 1 & 2, bath 1 & 2, kitchen/yard door)", unit: "no", qty: 6, rate: 0 },
  ] },
];

const SEED_AREAS = [
  { part: "LOBBY", partTitle: "MAIN LOBBY", areas: [
    { code: "L-A", title: "Reception Counter Table", dwg: "Dwg 06 — 3600L × 800D × 1100H top desk / 750H work desk", bqSec: "L", bqCodes: ["1", "2"],
      items: [
        { name: "Colour glass counter top, black", spec: "12mm thk, shaped top ±3600 × 800 with 500Ø round feature end (colour glass per Clarification #6)", qty: "1 pc", cat: "Glass & Mirror" },
        { name: "Laminate — Topmix TP7-53011G Volakas (marble)", spec: "Front & side fascia, ±1100H × 3600L wrap", qty: "±4–5 sheets", cat: "Laminate" },
        { name: "Laminate — white glossy", spec: "Inner / work-desk zone (counter centre)", qty: "±2 sheets", cat: "Laminate" },
        { name: "Laminate — white glossy (rear face) + black glossy", spec: "Black glossy for bottom plinth band (100H) & base", qty: "±2 sheets", cat: "Laminate" },
        { name: "Plywood / carcass board", spec: "18mm ply + 12mm backing for counter body, work desk 750H, top desk 1100H", qty: "±8–10 sheets", cat: "Timber & Board" },
        { name: "Drawer sets with lock & key", spec: "2 banks × 3 drawers (per rear elevation), c/w runners", qty: "6 drawers + 6 locksets", cat: "Hardware" },
        { name: "LED strip light", spec: "Under top-desk nose (full length ±3600) + floor cove", qty: "±10 m", cat: "LED & Electrical" },
        { name: "LED driver + aluminium casing + frosted diffuser cover", spec: "To suit strip runs", qty: "2–3 sets", cat: "LED & Electrical" },
        { name: "Cable/switch openings, grommets", spec: "Openings for switches per drawing", qty: "lot", cat: "Other" },
        { name: "Adhesive, edging (matching), screws/fixings", spec: "", qty: "lot", cat: "Paint & Consumables" },
      ],
      excluded: [] },
    { code: "L-B", title: "Front Backdrop behind Reception", dwg: "Dwg 02 — Backdrop 01; wall ±12100L × 4700H, slanted Panel A 750W / Panel B 1200W alternating", bqSec: "L", bqCodes: ["3", "4"],
      items: [
        { name: "Laminate — Topmix TP6-3361-M Midnight (marble)", spec: "Panel A & B faces, 2100H centre band", qty: "±10–12 sheets", cat: "Laminate" },
        { name: "Laminate — Topmix TP7-53011G Volakas", spec: "Centre feature panel (logo zone ±3607W)", qty: "±4 sheets", cat: "Laminate" },
        { name: "20mm black fluted panel", spec: "Top & bottom bands (960H each) across panel run", qty: "±20–24 m²", cat: "Fluted & Wainscoting" },
        { name: "20mm stainless steel strip, gold finish", spec: "Panel trims/junctions (was \"gold strip\" — Clarification #10)", qty: "±60–80 m", cat: "Metalwork" },
        { name: "Bronze mirror panels", spec: "Both side wall panels, full height", qty: "±12–15 m²", cat: "Glass & Mirror" },
        { name: "LED strip + drivers + casings", spec: "Backdrop wash lighting + behind bronze mirrors + behind slanted panels", qty: "±40 m + 6–8 drivers", cat: "LED & Electrical" },
        { name: "Plywood backing + timber framing", spec: "Fixing sub-frame on existing brick wall; slant angle adjusted on site", qty: "lot", cat: "Timber & Board" },
      ],
      excluded: ["Faithview logo wording — by sales team / signage package"] },
    { code: "L-C", title: "Left Wall — Company Milestones' Wall", dwg: "Dwg 05 — Backdrop 04", bqSec: "L", bqCodes: ["5"],
      items: [
        { name: "Laminate — Topmix TP7-53011G Volakas", spec: "Wall panels 2900H zone", qty: "±6 sheets", cat: "Laminate" },
        { name: "20mm black fluted panel", spec: "Side bands 1350–1650W × 1800H", qty: "±8 m²", cat: "Fluted & Wainscoting" },
        { name: "20mm stainless steel strip, gold finish", spec: "All panel trims", qty: "±30 m", cat: "Metalwork" },
        { name: "LED strip with aluminium casing + drivers", spec: "Light lines per elevation", qty: "±15 m + 3 drivers", cat: "LED & Electrical" },
        { name: "Plywood backing + framing", spec: "On existing brick/partition wall", qty: "lot", cat: "Timber & Board" },
      ],
      excluded: ["Milestones wording (gold colour) — by signage package"] },
    { code: "L-D", title: "ID Wall Finishes @ Front of Show Units A & B (×2)", dwg: "Dwg 05 — Backdrop 04 / unit signage walls, 1500W returns × 4700H — ×2 locations", bqSec: "L", bqCodes: ["6a", "6b"],
      items: [
        { name: "Laminate — Topmix TP7-53011G Volakas", spec: "Centre band (Type A / Type B wording zone, 3000H)", qty: "±6 sheets", cat: "Laminate" },
        { name: "20mm black fluted panel", spec: "Top (800–900H) & bottom (900H) bands + returns", qty: "±12 m²", cat: "Fluted & Wainscoting" },
        { name: "20mm stainless steel strip, gold finish", spec: "Trims", qty: "±40 m", cat: "Metalwork" },
        { name: "LED strip with casing + drivers", spec: "Per elevation", qty: "±16 m + 4 drivers", cat: "LED & Electrical" },
        { name: "Plywood/partition backing", spec: "Includes 500 deep signage return fin", qty: "lot", cat: "Timber & Board" },
      ],
      excluded: ["\"TYPE A / TYPE B\" wording (gold) & clear acrylic signage (500×700, wood frame black paint) — by sales team"] },
    { code: "L-E", title: "Sitting & Discussion Area / Pantry & Utility Wall", dwg: "Dwg 03 — Backdrop 02; ±10900L × 4700H, incl. 85\" TV zone", bqSec: "L", bqCodes: ["7"],
      items: [
        { name: "Laminate — Topmix TP7-53011G Volakas", spec: "Wall panels (3600W TV zone + flanks, 3800H)", qty: "±10 sheets", cat: "Laminate" },
        { name: "20mm stainless steel strip, gold finish", spec: "Panel joints (20mm reveals per elevation)", qty: "±50 m", cat: "Metalwork" },
        { name: "Bronze mirror wall panel", spec: "3200W × 4300H ads-flank zone + 450 bands", qty: "±14 m²", cat: "Glass & Mirror" },
        { name: "LED strip + drivers", spec: "Backlight behind bronze mirror + coves", qty: "±30 m + 5 drivers", cat: "LED & Electrical" },
        { name: "Plywood/timber additional backing support", spec: "For 85\" TV zone + recessed advertising panel zone (recess 20mm)", qty: "lot", cat: "Timber & Board" },
      ],
      excluded: ["Advertising panel & 85\" TV — supply & install by others"] },
    { code: "L-F", title: "Counter Table 02", dwg: "Dwg 07 — 3000L × 900D × 1100H / 900H rear work desk", bqSec: "L", bqCodes: ["8", "9"],
      items: [
        { name: "Colour glass counter top", spec: "12mm thk, ±3000 × 900 with radius corner", qty: "1 pc", cat: "Glass & Mirror" },
        { name: "Laminate — Topmix TP7-53011G Volakas", spec: "Top desk fascia (350H band)", qty: "±2 sheets", cat: "Laminate" },
        { name: "Laminate — Topmix TP6-3361-M Midnight", spec: "Above band (50H nose) & bottom band (300H) + plan face", qty: "±3 sheets", cat: "Laminate" },
        { name: "20mm black fluted panel", spec: "Front centre band 400H × full length", qty: "±5 m²", cat: "Fluted & Wainscoting" },
        { name: "Plywood / carcass board", spec: "Body + rear desk 900H, drawers bank", qty: "±6–8 sheets", cat: "Timber & Board" },
        { name: "Drawer sets with lock & key + runners", spec: "3 drawers (rear elevation)", qty: "3 + locksets", cat: "Hardware" },
        { name: "LED strip + driver + casing + frosted cover", spec: "Light trough above & below fluted band", qty: "±8 m + 2 sets", cat: "LED & Electrical" },
        { name: "Switch openings, grommets, edging, adhesive", spec: "", qty: "lot", cat: "Other" },
      ],
      excluded: [] },
    { code: "L-G", title: "Advertising Wall near Show Unit", dwg: "Dwg 04 — Backdrop 03; ads zone 3500W × 4700H + fluted flank", bqSec: "L", bqCodes: ["10"],
      items: [
        { name: "Bronze mirror panel", spec: "Border frame around ads zone (300 borders) + flank bands 1200H", qty: "±8 m²", cat: "Glass & Mirror" },
        { name: "20mm black fluted panel + 20mm SS gold strip", spec: "Flank wall (bands 1200 / 2260 / 1200H)", qty: "±8 m² + 20 m strip", cat: "Fluted & Wainscoting" },
        { name: "LED strip + drivers", spec: "Backlight behind bronze mirror", qty: "±15 m + 3 drivers", cat: "LED & Electrical" },
        { name: "Plywood backing/frame", spec: "On existing wall, 150 build-out", qty: "lot", cat: "Timber & Board" },
      ],
      excluded: ["Advertising illustration — by sales team"] },
    { code: "L-H", title: "Pantry Cabinet", dwg: "Dwg 08 — base 2000L × 600D × 900H; wall unit 1260+740 × 900H; total 2500H incl. shelves", bqSec: "L", bqCodes: ["11"],
      items: [
        { name: "Black Galaxy granite/stone counter top", spec: "±2000 × 600, cut-out for sink (sink zone 740W) — stone to client selection", qty: "1 slab", cat: "Stone" },
        { name: "Grey colour glass", spec: "Door & drawer fronts + wall-unit doors", qty: "±4 m²", cat: "Glass & Mirror" },
        { name: "Melamine/plywood carcass + internal shelves", spec: "Base + wall unit + 700H void zone", qty: "±6 sheets", cat: "Timber & Board" },
        { name: "Aluminium open shelves", spec: "On top of wall cabinet (per 3D)", qty: "2 tiers ±1260W", cat: "Metalwork" },
        { name: "Hinges (soft close), drawer runners, handles", spec: "", qty: "lot", cat: "Hardware" },
        { name: "Edging, adhesive, fixings", spec: "", qty: "lot", cat: "Paint & Consumables" },
      ],
      excluded: ["Single bowl sink & water tap — by others"] },
    { code: "L-I", title: "Public Toilet Mirrors", dwg: "Contractor's proposal item", bqSec: "L", bqCodes: ["12a", "12b", "12c", "12d"],
      items: [
        { name: "Mirror — Male toilet", spec: "±1950 × 900H, c/w LED light cove frame", qty: "1", cat: "Glass & Mirror" },
        { name: "Mirror — Female toilet", spec: "±2750 × 900H, c/w LED light cove frame", qty: "1", cat: "Glass & Mirror" },
        { name: "LED strip + driver + accessories", spec: "1 set per mirror", qty: "±10 m + 2 drivers", cat: "LED & Electrical" },
        { name: "Granite basin top material", spec: "Public toilet vanity tops (Clarification #9)", qty: "per site measure", cat: "Stone" },
        { name: "Architrave-type door frames", spec: "Public toilet doors (Clarification #2)", qty: "2 sets", cat: "Timber & Board" },
      ],
      excluded: [] },
  ] },
  { part: "MODEL", partTitle: "MODEL HOUSE BASE", areas: [
    { code: "M-A", title: "Model House Base", dwg: "Dwg 11 — 3900 × 2700 plan, 900H tapered base; top platform 3000 × 2100", bqSec: "M", bqCodes: ["1"],
      items: [
        { name: "Timber/plywood base structure", spec: "Carpenter-detail frame, stepped/tapered profile (bands 300/200/250/100H)", qty: "±10 sheets ply + framing timber", cat: "Timber & Board" },
        { name: "Laminate — Topmix TP7-53011G Volakas", spec: "20mm(H) rim border + sloped fascia bands", qty: "±4 sheets", cat: "Laminate" },
        { name: "Black glossy laminate", spec: "Lower fascia / plinth", qty: "±2 sheets", cat: "Laminate" },
        { name: "Black paint", spec: "Top platform surface (3000 × 2100)", qty: "±5 L", cat: "Paint & Consumables" },
        { name: "LED strip + drivers + casings", spec: "2 continuous light lines around perimeter (2 tiers)", qty: "±26 m + 4 drivers", cat: "LED & Electrical" },
      ],
      excluded: ["Model house / scale model — by others"] },
  ] },
  { part: "GARDEN", partTitle: "GARDEN SEATING AREA", areas: [
    { code: "G-A", title: "Garden Benches — Sitting Areas 01 & 02", dwg: "Dwg 10 — benches 3700L & 3300L, 700D × 450H, slat top 75thk, 50 legs", bqSec: "G", bqCodes: ["1", "3"],
      items: [
        { name: "Timber (solid/treated) slats & frame", spec: "Bench tops 3700 & 3300 × 700, 75mm thk finish, legs/stringers 375H", qty: "±1.6 m³ or equiv. sections", cat: "Timber & Board" },
        { name: "Timber sealer / outdoor coating", spec: "Timber finish", qty: "±5 L", cat: "Paint & Consumables" },
        { name: "Concealed brackets, SS screws", spec: "", qty: "lot", cat: "Hardware" },
      ],
      excluded: [] },
    { code: "G-B", title: "Planter Boxes — Sitting Areas 01 & 02", dwg: "Dwg 10 — 2500 / 2100 / 3300 L × 400W × 400H, 50thk walls, open/void top", bqSec: "G", bqCodes: ["2", "4"],
      items: [
        { name: "Cement board / block & render (or ply + render)", spec: "Box shells × 3 lengths", qty: "lot", cat: "Timber & Board" },
        { name: "Textured finish paint/coating", spec: "All exposed faces", qty: "±10 L", cat: "Paint & Consumables" },
        { name: "Waterproofing membrane (inner void)", spec: "Planting void protection", qty: "lot", cat: "Paint & Consumables" },
      ],
      excluded: [] },
  ] },
  { part: "TYPEA", partTitle: "SHOW UNIT TYPE A (2 BEDROOMS)", areas: [
    { code: "A-A", title: "Living Hall TV Area — Back Panel", dwg: "Living & Dining Sec. A; 2300W × 2250H, TV console 1500W", bqSec: "A", bqCodes: ["1", "2"],
      items: [
        { name: "Laminate — Topmix TP6-3321-G marble effect", spec: "Back panel", qty: "±3 sheets", cat: "Laminate" },
        { name: "Gold strips (SS gold finish) c/w LED light", spec: "Vertical reveals ±2 strips × 2250H (Clarification #10)", qty: "2 strips", cat: "Metalwork" },
        { name: "20mm fluted panel", spec: "Flank bands", qty: "lot", cat: "Fluted & Wainscoting" },
        { name: "TV cabinet — carcass ply + Topmix TS7-6026-G Creamy glossy beige", spec: "1500W × 500H, 3-bay", qty: "1 unit", cat: "Laminate" },
        { name: "Additional timber/steel backing for TV mounting", spec: "Inside wall (Clarification #4)", qty: "lot", cat: "Timber & Board" },
        { name: "LED strip + driver + accessories", spec: "", qty: "±6 m + 2 drivers", cat: "LED & Electrical" },
      ],
      excluded: [] },
    { code: "A-B", title: "Dining Area — Marble Effect & Wainscoting Wall", dwg: "Sec. A; 2600W zone", bqSec: "A", bqCodes: ["3", "4"],
      items: [
        { name: "25mm wainscoting wall panels", spec: "Pattern to client selection", qty: "±5 m²", cat: "Fluted & Wainscoting" },
        { name: "20mm wall fluted panel", spec: "1400W × 2250H feature", qty: "±3.5 m²", cat: "Fluted & Wainscoting" },
        { name: "10mm stainless steel strip, gold finish", spec: "", qty: "±15 m", cat: "Metalwork" },
        { name: "Tea mirror", spec: "Infill panels", qty: "±2 m²", cat: "Glass & Mirror" },
        { name: "LED strip + driver", spec: "", qty: "±6 m + 1 driver", cat: "LED & Electrical" },
      ],
      excluded: [] },
    { code: "A-C", title: "Living Hall — Behind Sofa", dwg: "Sec. B; 1200W panels × 2250H", bqSec: "A", bqCodes: ["5"],
      items: [
        { name: "20mm wood-grain beige fluted panels", spec: "", qty: "±3 m²", cat: "Fluted & Wainscoting" },
        { name: "Laminate — Topmix TS7-6026-G Creamy glossy beige + 10mm SS gold strip", spec: "", qty: "±2 sheets + 8 m strip", cat: "Laminate" },
        { name: "Painting / making good", spec: "", qty: "lot", cat: "Paint & Consumables" },
      ],
      excluded: [] },
    { code: "A-D", title: "Dining Hall & Kitchen/Yard Wall", dwg: "Sec. B", bqSec: "A", bqCodes: ["6", "7"],
      items: [
        { name: "20mm beige fluted wall panel", spec: "", qty: "±3 m²", cat: "Fluted & Wainscoting" },
        { name: "Marble effect laminate", spec: "Pattern to client selection", qty: "±2 sheets", cat: "Laminate" },
        { name: "Tea mirror", spec: "", qty: "±1.5 m²", cat: "Glass & Mirror" },
        { name: "Laminate — Topmix TS7-6026-G Creamy + 10mm SS gold strip with LED backlight", spec: "", qty: "±2 sheets + 8 m strip", cat: "Laminate" },
        { name: "LED strip + driver", spec: "", qty: "±5 m + 1 driver", cat: "LED & Electrical" },
      ],
      excluded: [] },
    { code: "A-D2", title: "Kitchen Cabinets (Type A)", dwg: "Kitchen & Yard sheet — keep ID finishes per Clarification #3; base 1750+915W, wall units 500H, tall 1350", bqSec: "A", bqCodes: [],
      items: [
        { name: "Kitchen base & wall cabinet carcass (ply/melamine)", spec: "", qty: "±8 sheets", cat: "Timber & Board" },
        { name: "Glossy beige colour glass door fronts", spec: "", qty: "±3 m²", cat: "Glass & Mirror" },
        { name: "Marble quartz stone counter top + marble-effect backwash panel", spec: "To client selection", qty: "±2.7 m run", cat: "Stone" },
        { name: "Aluminium shelf", spec: "", qty: "1 run", cat: "Metalwork" },
        { name: "Hinges, runners, handles", spec: "", qty: "lot", cat: "Hardware" },
      ],
      excluded: ["Cooker hood, stove, sink & tap — by client selection / others"] },
    { code: "A-E", title: "Master Bedroom Feature Wall", dwg: "Master Bed Sec. A; 2040W bedhead wall × 2700H", bqSec: "A", bqCodes: ["8", "9", "10"],
      items: [
        { name: "Fabric bedhead (upholstered)", spec: "1000H zone", qty: "±2 m²", cat: "Fabric & Upholstery" },
        { name: "Fabric wall panels", spec: "", qty: "±2.5 m²", cat: "Fabric & Upholstery" },
        { name: "75mm stainless steel strip, gold finish", spec: "Was gold laminate border (Clarification #10)", qty: "±6 m", cat: "Metalwork" },
        { name: "Laminate — Topmix TP7-53018M Volakas matte with LED strip", spec: "", qty: "±3 sheets", cat: "Laminate" },
        { name: "70mm wood-grain laminated border — Topmix TW8-3786VF Erfurt Acacia", spec: "", qty: "±5 m", cat: "Laminate" },
        { name: "LED strip + driver", spec: "", qty: "±5 m + 1 driver", cat: "LED & Electrical" },
        { name: "Bedside table ×1", spec: "Carcass + laminate to match", qty: "1 no", cat: "Timber & Board" },
      ],
      excluded: [] },
    { code: "A-F", title: "Master Bedroom Built-in Wardrobe", dwg: "Sec. A & B; 1400W + 300 return × 2300H, 400D", bqSec: "A", bqCodes: ["11", "12"],
      items: [
        { name: "Laminate — Topmix TS7-6026-G Creamy glossy beige", spec: "", qty: "±3 sheets", cat: "Laminate" },
        { name: "Laminate — Topmix TW10-53706 IM Bolzano Walnut wood grain", spec: "", qty: "±2 sheets", cat: "Laminate" },
        { name: "5mm groove line routing detail", spec: "Shop fabrication", qty: "lot", cat: "Other" },
        { name: "Carcass ply/melamine + shelving + hanging rail", spec: "", qty: "±5 sheets", cat: "Timber & Board" },
        { name: "LED strip + driver", spec: "", qty: "±4 m + 1 driver", cat: "LED & Electrical" },
      ],
      excluded: [] },
    { code: "A-G", title: "Bedroom 01 Feature Wall", dwg: "Bed 01 Sec. A; 1800W × 2000H panels", bqSec: "A", bqCodes: ["13", "14", "15"],
      items: [
        { name: "Bedhead — Topmix TS7-6026-G Creamy glossy beige with 5mm groove", spec: "", qty: "±2 sheets", cat: "Laminate" },
        { name: "Wall panel — TS7-6026-G Creamy with LED strip", spec: "", qty: "±2 sheets", cat: "Laminate" },
        { name: "Fabric wall panel", spec: "", qty: "±1.5 m²", cat: "Fabric & Upholstery" },
        { name: "Tea mirror with 5mm groove line", spec: "", qty: "±1.5 m²", cat: "Glass & Mirror" },
        { name: "LED strip + driver", spec: "", qty: "±4 m + 1 driver", cat: "LED & Electrical" },
        { name: "Bedside table ×1 — Topmix TW10-53006 VM Asaph Ash + TS7-6026-G Creamy", spec: "350W × 400H", qty: "1 no", cat: "Timber & Board" },
      ],
      excluded: [] },
    { code: "A-H", title: "Bedroom 01 Built-in Cabinet", dwg: "Sec. A & B; 1800W × 1450+1450H, 470D", bqSec: "A", bqCodes: ["16", "17"],
      items: [
        { name: "Laminate — Topmix TW10-53006 VM Asaph Ash", spec: "Shelves with LED strip, body, backing", qty: "±3 sheets", cat: "Laminate" },
        { name: "Laminate — Topmix TS7-6026-G Creamy", spec: "", qty: "±2 sheets", cat: "Laminate" },
        { name: "70mm border — Topmix TW8-3786VF Erfurt Acacia", spec: "", qty: "±4 m", cat: "Laminate" },
        { name: "Carcass + shelves", spec: "", qty: "±4 sheets", cat: "Timber & Board" },
        { name: "LED strip + driver", spec: "", qty: "±4 m + 1 driver", cat: "LED & Electrical" },
      ],
      excluded: [] },
    { code: "A-I", title: "Bathrooms 1 & 2 (×2 sets)", dwg: "", bqSec: "A", bqCodes: ["18", "19", "20"],
      items: [
        { name: "Vanity cabinet — Topmix TS4-1227 Dim Grey laminate", spec: "±500L × 450W × 400H", qty: "2 nos", cat: "Laminate" },
        { name: "Quartz stone counter top", spec: "100mm thk edge, cut-out for table-top basin", qty: "2 pcs", cat: "Stone" },
        { name: "Bronze full-height mirror c/w LED light cove", spec: "±900H × 1520L", qty: "2 nos", cat: "Glass & Mirror" },
        { name: "LED strip + driver + accessories", spec: "", qty: "2 sets (±6 m total)", cat: "LED & Electrical" },
      ],
      excluded: [] },
    { code: "A-J", title: "Door Frames (Type A)", dwg: "Foyer, master bed, bed 2, bath 1 & 2, kitchen/yard", bqSec: "A", bqCodes: ["21"],
      items: [
        { name: "70mm wood-grain laminate door frames — Topmix TW8-3786VF Erfurt Acacia", spec: "", qty: "6 nos", cat: "Timber & Board" },
      ],
      excluded: [] },
  ] },
  { part: "TYPEB", partTitle: "SHOW UNIT TYPE B (3 BEDROOMS)", areas: [
    { code: "B-A", title: "Living Hall — Sofa Wall", dwg: "L&D Sec. A; 1850W + flanks × 2250H", bqSec: "B", bqCodes: ["1", "2"],
      items: [
        { name: "20mm wood-grain fluted panel", spec: "", qty: "±3 m²", cat: "Fluted & Wainscoting" },
        { name: "Laminate — Topmix TS4-1223 Gainsboro Grey matte, 5mm groove line", spec: "", qty: "±3 sheets", cat: "Laminate" },
        { name: "Additional structural backing for TV", spec: "Clarification #4", qty: "lot", cat: "Timber & Board" },
        { name: "LED strip + driver", spec: "", qty: "±5 m + 1 driver", cat: "LED & Electrical" },
      ],
      excluded: [] },
    { code: "B-B", title: "Living Hall TV Back Panel", dwg: "Sec. C; 1500W console, wall 2250H", bqSec: "B", bqCodes: ["3", "4"],
      items: [
        { name: "Laminate — Topmix TP6-3331-G Levanto Marble, 5mm groove", spec: "", qty: "±3 sheets", cat: "Laminate" },
        { name: "Laminate — Topmix TW8-3758 SE Sokoto Chestnut wood effect, 5mm groove", spec: "", qty: "±2 sheets", cat: "Laminate" },
        { name: "10mm stainless steel strip, gold finish", spec: "", qty: "±10 m", cat: "Metalwork" },
        { name: "TV cabinet — Topmix TS6-5018 G Black glossy + TP6-3331-G Levanto top", spec: "Carcass + 2 sheets", qty: "1 unit", cat: "Laminate" },
        { name: "Tea mirror", spec: "", qty: "±1.5 m²", cat: "Glass & Mirror" },
        { name: "TV structural backing", spec: "", qty: "lot", cat: "Timber & Board" },
        { name: "LED strip + driver", spec: "", qty: "±5 m + 1 driver", cat: "LED & Electrical" },
      ],
      excluded: [] },
    { code: "B-C", title: "Dining Area", dwg: "Sec. A & B; 620/750/620 panel rhythm × 2250H", bqSec: "B", bqCodes: ["5", "6"],
      items: [
        { name: "Laminate — Topmix TS4-1223 Gainsboro Grey, 5mm groove @ 750mm ht", spec: "", qty: "±3 sheets", cat: "Laminate" },
        { name: "Laminate — Topmix TP6-3331-G Levanto Marble", spec: "", qty: "±2 sheets", cat: "Laminate" },
        { name: "Laminate — Topmix TW8-3758 SE Sokoto Chestnut, 5mm groove", spec: "", qty: "±2 sheets", cat: "Laminate" },
        { name: "Tea mirror with LED light", spec: "", qty: "±2 m²", cat: "Glass & Mirror" },
        { name: "10mm SS gold strip", spec: "", qty: "±8 m", cat: "Metalwork" },
        { name: "LED strip + driver", spec: "", qty: "±5 m + 1 driver", cat: "LED & Electrical" },
      ],
      excluded: [] },
    { code: "B-C2", title: "Kitchen Cabinets (Type B)", dwg: "Kitchen & Foyer sheet — keep ID finishes per Clarification #3", bqSec: "B", bqCodes: [],
      items: [
        { name: "Base + wall cabinet carcass", spec: "", qty: "±8 sheets", cat: "Timber & Board" },
        { name: "Laminate door fronts & quartz stone top per ID drawing finishes", spec: "Client final selection", qty: "lot", cat: "Stone" },
        { name: "Hinges, runners, handles, aluminium accessories", spec: "", qty: "lot", cat: "Hardware" },
      ],
      excluded: ["Stove, hood, sink & tap — by others"] },
    { code: "B-D", title: "Master Bedroom Feature Wall", dwg: "Master Bed Sec. A", bqSec: "B", bqCodes: ["7", "8", "9"],
      items: [
        { name: "Fabric bedhead with LED backlight", spec: "1000mm H", qty: "±2.5 m²", cat: "Fabric & Upholstery" },
        { name: "25mm wood fluted panel", spec: "Above bedhead", qty: "±2 m²", cat: "Fluted & Wainscoting" },
        { name: "Laminate — Topmix TP7-53015 G Imola Marble, 5mm groove + 10mm SS gold strip", spec: "", qty: "±3 sheets + 8 m strip", cat: "Laminate" },
        { name: "Wall panel with 20mm wainscoting", spec: "Pattern to client selection", qty: "±3 m²", cat: "Fluted & Wainscoting" },
        { name: "LED strip + driver", spec: "", qty: "±5 m + 1 driver", cat: "LED & Electrical" },
        { name: "Bedside tables ×2 — Topmix TW8-3758 SE Sokoto Chestnut + TS6-5223 G Gainsboro Grey", spec: "", qty: "2 nos", cat: "Timber & Board" },
      ],
      excluded: [] },
    { code: "B-E", title: "Master Wardrobe + Dressing Table", dwg: "Sec. B", bqSec: "B", bqCodes: ["10", "11", "12"],
      items: [
        { name: "Wardrobe — Topmix TW8-3758 SE Sokoto Chestnut (5mm groove) + TS6-5223 G Gainsboro Grey (5mm groove)", spec: "", qty: "±5 sheets + carcass ±5 sheets", cat: "Laminate" },
        { name: "Dressing table — Sokoto Chestnut backing & top, mirror with LED backlight, drawer in TS6-5223 G Gainsboro Grey", spec: "Incl. mirror ±450 × 900", qty: "1 set", cat: "Timber & Board" },
        { name: "LED strip + driver", spec: "", qty: "±4 m + 1 driver", cat: "LED & Electrical" },
      ],
      excluded: [] },
    { code: "B-F", title: "Bedroom 01 Feature Wall", dwg: "Bed 01 Sec. B", bqSec: "B", bqCodes: ["13", "14"],
      items: [
        { name: "Bedhead — Maica M30207 Messiera Cherry wood-grain laminate", spec: "", qty: "±2 sheets", cat: "Laminate" },
        { name: "25mm wood fluted panel", spec: "", qty: "±2 m²", cat: "Fluted & Wainscoting" },
        { name: "LED strip + driver", spec: "", qty: "±4 m + 1 driver", cat: "LED & Electrical" },
        { name: "Bed base by carpenter — plywood/timber frame", spec: "", qty: "lot", cat: "Timber & Board" },
      ],
      excluded: [] },
    { code: "B-G", title: "Bedroom 01 Built-in Cabinet", dwg: "Sec. A", bqSec: "B", bqCodes: ["15", "16"],
      items: [
        { name: "Laminate — Topmix TS6-5223 G Gainsboro Grey glossy grey", spec: "", qty: "±3 sheets", cat: "Laminate" },
        { name: "Laminate — Maica M30207 Messiera Cherry with LED strip", spec: "Backing, handle detail, desk top", qty: "±3 sheets", cat: "Laminate" },
        { name: "Carcass + shelves", spec: "", qty: "±4 sheets", cat: "Timber & Board" },
        { name: "LED strip + driver", spec: "", qty: "±4 m + 1 driver", cat: "LED & Electrical" },
      ],
      excluded: [] },
    { code: "B-H", title: "Bedroom 02 Feature Wall", dwg: "Bed 02 sheet", bqSec: "B", bqCodes: ["17", "18"],
      items: [
        { name: "Fabric wall panel", spec: "", qty: "±2.5 m²", cat: "Fabric & Upholstery" },
        { name: "Laminate — Topmix TP7-53011 G Volakas Marble with LED light", spec: "", qty: "±2 sheets", cat: "Laminate" },
        { name: "LED strip + driver", spec: "", qty: "±4 m + 1 driver", cat: "LED & Electrical" },
      ],
      excluded: [] },
    { code: "B-I", title: "Bedroom 02 Built-in Cabinet", dwg: "Per BQ item 19", bqSec: "B", bqCodes: ["19", "20"],
      items: [
        { name: "Laminate — Topmix TS7-6026 G Creamy glossy beige", spec: "", qty: "±3 sheets", cat: "Laminate" },
        { name: "Tea mirror", spec: "", qty: "±1 m²", cat: "Glass & Mirror" },
        { name: "Laminate — Maica M3042 English Oak with LED strip", spec: "Shelves", qty: "±2 sheets", cat: "Laminate" },
        { name: "Carcass + shelves", spec: "", qty: "±4 sheets", cat: "Timber & Board" },
        { name: "LED strip + driver", spec: "", qty: "±4 m + 1 driver", cat: "LED & Electrical" },
      ],
      excluded: [] },
    { code: "B-J", title: "Bathrooms 1 & 2 (×2 sets)", dwg: "", bqSec: "B", bqCodes: ["21", "22", "23"],
      items: [
        { name: "Vanity cabinet — Topmix TS4-1227 Dim Grey", spec: "±500 × 450 × 400H", qty: "2 nos", cat: "Laminate" },
        { name: "Quartz stone top", spec: "100mm thk, basin cut-out", qty: "2 pcs", cat: "Stone" },
        { name: "Bronze full-height mirror c/w LED cove", spec: "±900H × 1140L", qty: "2 nos", cat: "Glass & Mirror" },
        { name: "LED strip + driver + accessories", spec: "", qty: "2 sets (±5 m)", cat: "LED & Electrical" },
      ],
      excluded: [] },
    { code: "B-K", title: "Door Frames (Type B)", dwg: "Foyer, master bed, bed 1 & 2, bath 1 & 2, kitchen/yard", bqSec: "B", bqCodes: ["24"],
      items: [
        { name: "70mm wood-grain laminate door frames — Topmix TW8-3786VF Erfurt Acacia", spec: "", qty: "6 nos", cat: "Timber & Board" },
      ],
      excluded: [] },
  ] },
  { part: "GEN", partTitle: "GENERAL / SITE-WIDE", areas: [
    { code: "X-A", title: "Hidden Door & Public Toilet Doors", dwg: "Tender clarifications #2 & #5", bqSec: "", bqCodes: [],
      items: [
        { name: "Hidden-door set (utility room)", spec: "Hidden door type per Clarification #5", qty: "1 set", cat: "Timber & Board" },
      ],
      excluded: [] },
    { code: "X-B", title: "Preliminaries & Insurance", dwg: "BQ Preliminaries section", bqSec: "P", bqCodes: ["1", "2"],
      items: [
        { name: "Insurance (Car, WC)", spec: "Contractor all-risk & workmen compensation", qty: "1 L/sum", cat: "Other" },
      ],
      excluded: [] },
  ] },
];

const STAGES = [
  { k: 'measure', label: 'Site measurement', w: 5 },
  { k: 'sample',  label: 'Samples approved', w: 10 },
  { k: 'order',   label: 'Materials ordered', w: 10 },
  { k: 'fab',     label: 'Fabrication', w: 30 },
  { k: 'deliver', label: 'Delivered to site', w: 5 },
  { k: 'install', label: 'Installation', w: 30 },
  { k: 'light',   label: 'Lighting & electrical', w: 5 },
  { k: 'qc',      label: 'Touch-up & QC', w: 5 },
];

const BUY_STATUSES = [
  { k: 'pending',   label: 'To order',       color: '#64748b' },
  { k: 'sample',    label: 'Sample pending', color: '#d97706' },
  { k: 'ordered',   label: 'Ordered',        color: '#2563eb' },
  { k: 'delivered', label: 'Delivered',      color: '#7c3aed' },
  { k: 'installed', label: 'Installed',      color: '#16a34a' },
  { k: 'na',        label: 'N/A',            color: '#94a3b8' },
];

const BUY_CATEGORIES = ['Laminate', 'Fluted & Wainscoting', 'Glass & Mirror', 'Stone',
  'LED & Electrical', 'Metalwork', 'Timber & Board', 'Fabric & Upholstery',
  'Hardware', 'Paint & Consumables', 'Other'];
