// Daily-report PDF generation (jsPDF) + Web Share API with download fallback.
import { jsPDF } from 'jspdf'
import type { Project, Report } from '../types'
import { fmtDay, fmtFull } from './dates'
import { photoGet } from '../db'

const TEAL = '#0F766E'
const INK = '#1B1F1E'
const GRAY = '#6B7370'

async function blobToDataUrl(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const r = new FileReader()
    r.onload = () => resolve(r.result as string)
    r.onerror = () => reject(r.error)
    r.readAsDataURL(blob)
  })
}

export async function buildReportPdf(project: Project, report: Report): Promise<Blob> {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const W = 210
  const M = 18
  let y = 22

  doc.setFillColor(TEAL)
  doc.rect(0, 0, W, 4, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.setTextColor(INK)
  doc.text('Daily Site Report', M, y)
  y += 8
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.setTextColor(GRAY)
  doc.text(`${fmtDay(report.dateISO)} · ${project.name}`, M, y)
  y += 4
  doc.text(report.complete ? 'Status: COMPLETE' : 'Status: NO MATERIAL LOG', M, y)
  y += 10

  // Photos
  const photoBlobs: Blob[] = []
  for (const id of report.photoIds) {
    const b = await photoGet(id)
    if (b) photoBlobs.push(b)
  }
  if (photoBlobs.length > 0) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.setTextColor(INK)
    doc.text('Site photos', M, y)
    y += 5
    const size = 40
    const gap = 5
    let x = M
    for (const b of photoBlobs) {
      if (x + size > W - M) {
        x = M
        y += size + gap
      }
      if (y + size > 280) break
      try {
        const dataUrl = await blobToDataUrl(b)
        doc.addImage(dataUrl, 'JPEG', x, y, size, size)
      } catch {
        // skip un-decodable photo
      }
      x += size + gap
    }
    y += size + 10
  }

  const section = (title: string) => {
    if (y > 260) {
      doc.addPage()
      y = 22
    }
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.setTextColor(INK)
    doc.text(title, M, y)
    y += 6
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10.5)
  }

  section('Manpower on site')
  const manEntries = Object.entries(report.manpower).filter(([, n]) => n > 0)
  const manTotal = manEntries.reduce((a, [, n]) => a + n, 0)
  doc.setTextColor(GRAY)
  if (manEntries.length === 0) {
    doc.text('None recorded', M, y)
    y += 6
  } else {
    for (const [name, n] of manEntries) {
      doc.text(`${name}`, M, y)
      doc.text(`${n} workers`, W - M, y, { align: 'right' })
      y += 5.5
    }
    doc.setTextColor(INK)
    doc.text('Total', M, y)
    doc.text(`${manTotal} workers`, W - M, y, { align: 'right' })
    y += 6
  }
  y += 4

  section('Material used')
  doc.setTextColor(GRAY)
  if (report.materials.length === 0) {
    doc.text('No material log', M, y)
    y += 6
  } else {
    for (const m of report.materials) {
      doc.text(m.name, M, y)
      doc.text(`${m.qty} ${m.unit}`, W - M, y, { align: 'right' })
      y += 5.5
    }
  }
  y += 4

  section('Work done summary')
  doc.setTextColor(GRAY)
  const summaryLines = doc.splitTextToSize(report.summary || '—', W - M * 2)
  doc.text(summaryLines, M, y)
  y += summaryLines.length * 5 + 4

  section('Issues / blockers')
  doc.setTextColor(GRAY)
  const issueLines = doc.splitTextToSize(report.issues || 'None reported', W - M * 2)
  doc.text(issueLines, M, y)
  y += issueLines.length * 5 + 8

  doc.setFontSize(9)
  doc.setTextColor('#9AA09C')
  doc.text(`Generated by Reno Tracker · ${fmtFull(report.dateISO)}`, M, 290)

  return doc.output('blob')
}

/** Share via the Web Share API (files) when available, otherwise download. */
export async function sharePdf(blob: Blob, filename: string): Promise<'shared' | 'downloaded'> {
  const file = new File([blob], filename, { type: 'application/pdf' })
  const nav = navigator as Navigator & { canShare?: (d: ShareData) => boolean }
  if (nav.share && nav.canShare?.({ files: [file] })) {
    try {
      await nav.share({ files: [file], title: filename })
      return 'shared'
    } catch {
      // user cancelled or share failed — fall through to download
    }
  }
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  setTimeout(() => URL.revokeObjectURL(url), 30_000)
  return 'downloaded'
}
